# Uncomment the next line to define a global platform for your project

platform :ios, '16.0'
# platform :ios, '9.0'

use_frameworks!

workspace 'Modularization'
 
target 'MyRestaurantApp' do
  # Pods for App
	 pod 'RealmSwift'
	 pod 'SDWebImageSwiftUI', '>= 0'
	 pod 'Alamofire'
end
 
target 'Core' do
  project '../Modules/Core/Core'
	# pod 'Alamofire'

end

target 'Home' do
  project '../Modules/Home/Home'
	# pod 'Alamofire'

end

target 'Detail' do
  project '../Modules/Detail/Detail'
	# pod 'Alamofire'

end

target 'Favorite' do
  project '../Modules/Favorite/Favorite'
	pod 'RealmSwift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Realm'
      create_symlink_phase = target.shell_script_build_phases.find { |x| x.name == 'Create Symlinks to Header Folders' }
      create_symlink_phase.always_out_of_date = "1"
    end
  end
end